#!/usr/bin/env bash
# Displaying "Best School" in script 10 times
for n in "Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School"
do
	echo $n
done
