#!/usr/bin/env bash
# 4 Bad luck, 8 is your chance
x=1
while [ $x -le 10 ];
do
if [ $x -eq 4 ];
then 
	echo "bad luck"
elif [ $x -eq 8 ];
then
	echo "good luck"
else 
	echo "Best School"
fi
let x+=1
done
