#!/usr/bin/env bash
# To file, or not to file
FILE1=school
if [ -e $FILE1 ];then
    echo "$FILE1 file exists"
	
    if [ -s $FILE1 ]; then
	echo "$FILE1 file is not empty"
    else
	echo "$FILE1 file is empty"
    fi

    if [ -f $FILE1 ]; then
	echo "$FILE1 file is a regular file"
    fi

else
    echo "$FILE1 file does not exist"

fi
